### PR TITLE
added author and license to connman.c

### PR DESCRIPTION
**Pull request by andrew-bibb**
Here you go.

### CODE REVIEW

**Comment by TrilbyWhite** [comment]
Thanks.

**Comment by andrew-bibb** [comment]
Holy cow! I saw your connman.c suggestions last night and I was going to start working on the sleep one this evening, and I see you are about 3/4 the way through with it.  I do apologize, I really did not mean to add any additional work to your plate.  

If you want me to pick anything up, or rework anything, please feel free to ask.  As I'm sure you've ascertained, I'm swimming in water way over my head on this, but all the same I'm willing to give anything a shot.  

I did see the note about maybe changing the bars to icons, and I just wanted to mention that the reason I fixed them at 13px is that anything taller gets cut off in the i3-wm bar (that includes the mail box icons).  I was going to move the constant out of the main code to become a user defined variable in config.h. I believe the Freedesktop.org spec says 22x22, but i3, at least on my computer, is running much smaller.

Anyway, if you need me to do anything please don't hesitate to ask.  

A-

**Comment by TrilbyWhite** [comment]
Oh it's no work - I code for fun, and you gave me a new challenge to tinker with ;)

The 'icons' I'm referring to are not images, they're just byte arrays like the mail icon.  There is no standard size for tray icons.  Technically the standard suggests that client programs should adjust to whatever the tray geometry is.  I've thought about adding another Atom to fetch the actual tray geometry - it is very easy to do - but I realized it would serve little purpose[1].  The config.h is meant to be edited by users; if my mail icon is too big, create a new one that is right for your bar.  We do all likely have different bar sizes, but none of us likely have bars that are frequently changing size.

As for the progress I've made, I've only cleaned up the main loop a tiny bit.  I'd really like to get rid of phtread.  Multithreading is buggy as hell - particularly in this sort of use.  And it is really a pain to debug.  The thread can be removed, and the timed loop removed by solving one puzzle - it's a puzzle I've leared defintely has a solution, but I am not familiar with it yet: it is to use a DBusWatch and a select loop.  You can see an example of a select main loop on line 235-255 of my project Alopex in src/xlib.c.  Select allows the loop to wait for something to do, and that 'something' can come from a variety of source.  In alopex the select loop waits for events from the xserver, or for input on the stdin.  In the connman module, the select loop would wait for events from the xserver or from the DBusWatch.

I've found documentation on acquiring a filedescriptor (needed for select) from a DBusWatch, but this is the first I've ever tinkered with dbus programming, and I'm not quite sure how to initalize the Watch.

As I've been learning about this, it occurred to me that it would be _very_ easy to have a more generic dbus listener.  With some parameters filled from config.h, the same module could listen for connman signals, NetworkManager signals, or any other, and display icons depending on the content of the message recieved.  I've just pushed the current state of this dbus_listener.c to github.  I'm still stuck on the proper initialization of the DBusWatch.  The documentation is not great, and I can't find any examples.  All the available examples use a glib main loop - and while many say a select loop can work, none show how.

So that's where I currently am.  If you find a (good) example of a dbus watch select loop I could very easily put the rest together.

[1] Knowing the tray size is useful for programs that would scale their icons.  This would be simple with an added graphics library (e.g. cairo) but I want blueplate to stay maniacally minimal.  There are enough featureful tray programs out there already - I'm strict on the simplicitiy of blueplate as that is the one unique feature it offers.  This is also what lead to my comments on connman.c: I'm happy to keep it as part of the project if it works, but until it meets my crazy demands of simplicity, it wont be a 'featured' module.

**Comment by TrilbyWhite** [comment]
As much is lost in online communication I want to emphasize that I am grateful for the connman module.  My critiques are only ideas on how it can be perfected - it was excellently written code, particularly if you are new to C.

**Comment by andrew-bibb** [comment]
Thank you, as long as you're having fun I feel much better about it.  

I know what you mean about not being able to find much documentation on dbus.  I found the best place to look is in the dbus source tree, particularly the tools directory.  I had printed out the dbus-monitor.c program which seemed to have a good example of the bus_connection_read_write_dispatch function in it (to attack the sleep loop) and I also have a printout of the dbus-mainloop.c file (that one is in the main dbus directory) which seems to have a lot of stuff about the watches in it.  That runs for quite a few pages and I've barely looked at it other than that.

I was having a blast with this, probably because I was learning a lot and it is kind of fun mucking around with this low level stuff.  Maybe I'm also getting a bit bored with having QT do everything for me.

**Comment by andrew-bibb** [comment]
Just a quick note that the sleep loop is gone in my "working" copy.  Replaced with dbus_connection_read_write_dispatch. 

Still threading, but getting rid of that is next on the hit parade.

[edit] replaced "forking" with "threading" in last line.
A-

**Comment by TrilbyWhite** [comment]
I think I just figured out the hard part.  Check out dbus_listener.c.  I've plugged pieces of blueplate.c into that file so dbus_listener can be compiled as a standalone program for now for testing.  I don't have connman, nor any other service sending dbus messages, so I can't do much to really test this.  But if you wanted to try it out, it should currently spit out a block of information whenever connman sends a dbus message (but be sure to adjust the "rule" string).

I just finished some binge coding, but I may try to start testing this out and polishing it up next week unless you beat me to it.

**Comment by andrew-bibb** [comment]
A couple of things.  One is I had to change line 106 to:

> DBusConnection *conn = dbus_bus_get(DBUS_BUS_SYSTEM, NULL);

Connman lives on the system bus, not the session bus.

To build I had to use this:

> gcc -o dbus_listener dbus_listener.c $(pkg-config --cflags dbus-1 x11) $(pkg-config --libs dbus-1 x11)

Those two are minor, but this one you are not going to be happy with.  I do get a block of information printed from Connman:

> sender=org.freedesktop.DBus
>   serial=2
>   path=/org/freedesktop/DBus
>   interface=org.freedesktop.DBus
>   member=NameAcquired

According to HTOP the  CPU runs right up to 100%, but only after I get the first block of text.  Before that it is sitting there at 0% CPU and 0.1% Memory.

**Comment by TrilbyWhite** [comment]
Hmm, odd.  That block isn't from connman though.  I get that block.  Did you change the "rule" string?

(pkg-config should work with cflags and libs at the same time as in the comment - it compiles and runs fine here)

**Comment by andrew-bibb** [comment]
Yes I did, in fact I needed to add a semi-colon to the end of the line.  Also commented out the line above which was active.

> //const char *rule = "eavesdrop=true,type='signal'";
> //const char *rule = "eavesdrop=true";
> const char *rule = "eavesdrop=true,type='signal',interface='net.connman.Manager'";

The program was just sitting there until I went into another terminal and typed "connmanctl" then "enable offline".  At that point the block came up instantly.  No other blocks appeared when I type any other commands, for instance "disable offline".  I was assuming it was because the CPU ran to 100%, but I see now, that text block is not even from connman.

It looks like the text block is only coming up when DBUS processes a signal on net.connman.Manager.  I tried with CMST (which talks to connman) and it was the same as if I typed the command from a terminal.  Killed dbus_listener, restarted, and sent a bunch of messages using notify-send to the notification daemon.  These messages are sent via dbus and dbus_lisener just sat there, no text block printed.  It appears to me that the watch is working properly.

**Comment by TrilbyWhite** [comment]
I just pushed a fix for the 100% cpu use.  I missed a step in marking the watch as readable.  It seems this may have also been preventing anything other than the very first message from being recieved.  I may have to install connman in the next couple weeks to really be able to test this.

**Comment by andrew-bibb** [comment]
Just tested the latest.  Better, this time. I'm getting a few Connman messages, then the CPU runs right up and no other text blocks are sent.  PropertyChanged is a signal so that is looking good.  

sender=org.freedesktop.DBus
    serial=2
    path=/org/freedesktop/DBus
    interface=org.freedesktop.DBus
    member=NameAcquired
sender=:1.2
    serial=348
    path=/
    interface=net.connman.Manager
    member=PropertyChanged
sender=:1.2
    serial=355
    path=/
    interface=net.connman.Manager
    member=PropertyChanged

I've got a few other things I need to do this evening, but I'll take a look over the weekend and see if I can lock down the step where the CPU goes wild.

**Pull request merged**
