### PR TITLE
Working

### PR DESCRIPTION
**Pull request by andrew-bibb**
I've hacked on the dbus_listener and eliminated the 100% CPU usage.  Basically replacing the pop function with  read_write_dispatch function.  I now get a block of text that continually updates and CPU essentially zero.

I'm not sure you can (or want) to do a pull on this.  I've mainly done it to give you something to compare with.  

What I'm not sure on is with the read_write_dispatch going can I then test for the mouse click on the icon.

### CODE REVIEW

**Comment by TrilbyWhite** [comment]
My last push fixed the 100% CPU use here - it was just missing the one line.  Did you try that?

**Comment by andrew-bibb** [comment]
I think one of my messages got lost in the going back and forth.  I did try the last push with the 100% fix.  I could get 3 blocks of text, first one the generic DBus message we were getting, the last two from Connman Manager.  After that it would ramp up to 100% again.

In this quasi pull request (not really a pull, just seemed the best way to get the code to you) I replaced the dbus pop function with the read_write_dispatch.  As I understand the DBus code if you are going to use pop you need the usleep loop.  With pop once you clear out the incoming message queue your while loop takes over and runs the CPU usage right up.

**Comment by TrilbyWhite** [comment]
That's the point of the select, though.  The select blocks until there is no data to be read.

**Comment by andrew-bibb** [comment]
Went back and started with a clean copy.  I also put in a couple of printf statements, one in the outer while loop called running, one in the inner pop loop.  If I'm reading the output correct, once the queue is empty we return to the outer running loop which is when the CPU goes to 100.  To get the output below I put another condition in the outer while to terminate once the counter got to 15.

Inside the running loop iteration: 0
Inside the running loop iteration: 1
Inside the pop loop, iteration: 0
sender=org.freedesktop.DBus
    serial=2
    path=/org/freedesktop/DBus
    interface=org.freedesktop.DBus
    member=NameAcquired
Inside the pop loop, iteration: 1
sender=:1.3
    serial=439
    path=/
    interface=net.connman.Manager
    member=PropertyChanged
Inside the running loop iteration: 2
Inside the running loop iteration: 3
Inside the running loop iteration: 4
Inside the running loop iteration: 5
Inside the running loop iteration: 6
Inside the running loop iteration: 7
Inside the running loop iteration: 8
Inside the running loop iteration: 9
Inside the running loop iteration: 10
Inside the running loop iteration: 11
Inside the running loop iteration: 12
Inside the running loop iteration: 13
Inside the running loop iteration: 14

**Comment by TrilbyWhite** [comment]
I have no idea - I'm still unable to replicate the high cpu use here.

**Comment by andrew-bibb** [comment]
I've been putting fprint statments all over the place and I think what is happening is that once a member of the fds set is marked ready for reading the `ret = select(nfd, &fds, 0, 0, NULL);`  line no longer blocks.  It keeps saying yep, there are things to read.  

I've tried hacking several things, close(), and resetting the fds, but after several hours I still only have a vague idea of where you are going with this.  Much better than when I started when I had no idea, and if my vague idea pans out this is going to be way cool.

The only thing that has stopped the CPU runup, but which also stopped the entire thing, was setting wfd=0 after the while loop processed the buffer.  I know that is totally wrong, but I can't figure out how to reset wfd (and any other members of the fds set).

**Comment by TrilbyWhite** [comment]
And you definitely have the "dbus_watch_handle(w, DBUS_WATCH_READABLE);" in whatever is called by the select loop?

**Comment by andrew-bibb** [comment]
Yes I do, it is the last line of  handle() function, and that function is called after select fires.  All that is unchanged from your code.

The only modifications I've done (before I started hacking around) were to change the rule to the net.connman.Manager one, and change the bus from SESSION to SYSTEM.

**Comment by andrew-bibb** [comment]
Finally figured it out.  You need to remove this line from your handle() function:
`dbus_watch_handle(w, DBUS_WATCH_READABLE);`

And place it between the if and while statements in your main loop:

```
    if (wfd && FD_ISSET(wfd, &fds)) {
      dbus_watch_handle(w, DBUS_WATCH_READABLE);
      while ( (msg=dbus_connection_pop_message(conn)) )
       handle(msg);
    }
```

I'm redoing the connman module to use this formulation, and was going to close this PR

**Pull request closed without merging**
